# services:
#   nuxt:
#     build:
#       context: .
#     image: nuxt-app
#     container_name: nuxt-app
#     ports:
#       - ${OUTPUT_PORT}:3000
#       - 24678:24678
# # Remember to see the pages on port OUTPUT_PORT in .env

services:
  nuxt-docker-example:
    container_name: nuxt-docker-example
    build:
      context: .
      # dockerfile: DockerFile
    ports:
      - '3000:3000'
      - '24678:24678'
